### ISSUE TITLE
the files are fucked

### ISSUE THREAD

**Issue by MysticalUshanka** [potablepotato/COMP101-SEMPROJ#1]
the files are fucked. whoever owns the project (xiaodeng i think) needs to delete files and mess with it because currently it doesn't seem to work? something's up and I'm not sure what it is and it has something to do with the fact that we're cloning and submitting more code rather than replacing. somebody please fix because I don't know how. All I know is that the files inside the zip folder contain everything up to when I integrated the start menu.

**Comment by potablepotato** [comment]
deleted COMP101SemProj.pde, building.pde, player.pde files from >2 weeks ago
I'll be integrating my code with what's on github before adding new features and moving everything into a single .pde file to simplify downloads
